apiVersion: v1
kind: Namespace
metadata:
  name: metrics-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: metrics-server
  namespace: metrics-server
spec:
  selector:
    matchLabels:
      k8s-app: metrics-server
  template:
    metadata:
      labels:
        k8s-app: metrics-server
    spec:
      containers:
        - name: metrics-server
          image: k8s.gcr.io/metrics-server/metrics-server:v0.6.4
          args:
            - --kubelet-insecure-tls
            - --kubelet-preferred-address-types=InternalIP
          ports:
            - containerPort: 4443
---
apiVersion: v1
kind: Service
metadata:
  name: metrics-server
  namespace: metrics-server
spec:
  ports:
    - port: 443
      targetPort: 4443
  selector:
    k8s-app: metrics-server
