apiVersion: apps/v1
kind: Deployment
metadata:
  name: browserquest
  namespace: browserquest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: browserquest
  template:
    metadata:
      labels:
        app: browserquest
    spec:
      containers:
        - name: browserquest
          image: maxbdk/browserquest:test
          ports:
            - containerPort: 8080
              name: http
            - containerPort: 8000
              name: websocket
          resources:
            requests:
              cpu: 100m
            limits:
              cpu: 200m
