apiVersion: apps/v1
kind: Deployment
metadata:
  name: browserquest
  namespace: browserquest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: browserquest
  template:
    metadata:
      labels:
        app: browserquest
    spec:
      containers:
        - name: browserquest
          image: jeck0v/browserquest:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
