apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: browserquest-hpa
  namespace: browserquest
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: browserquest
  minReplicas: 3
  maxReplicas: 8
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
