apiVersion: v1
kind: Service
metadata:
  name: browserquest
  namespace: browserquest
spec:
  selector:
    app: browserquest
  ports:
    - name: http
      port: 80
      targetPort: 8080
    - name: websocket
      port: 8000
      targetPort: 8000

