apiVersion: v1
kind: Service
metadata:
  name: browserquest
  namespace: browserquest
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30000
  selector:
    app: browserquest
