version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "8080:8080"
      - "8000:8000"
    command: sh -c "cd client && npx http-server -p 8080 & node server/js/main.js"