apiVersion: v1
kind: Service
metadata:
  name: browserquest-service
  namespace: default
  labels:
    app: browserquest
spec:
  selector:
    app: browserquest
  ports:
    - name: http
      port: 80
      targetPort: 80
    - name: websocket
      port: 8000
      targetPort: 8000
  type: ClusterIP
