apiVersion: v1
kind: Service
metadata:
  name: client-service
  labels:
    app: browserquest
    tier: client
spec:
  selector:
    app: browserquest
    tier: client
  ipFamilyPolicy: PreferDualStack
  ipFamilies:
    - IPv6
    - IPv4
  ports:
    - name: http
      port: 80
      targetPort: 80
  type: ClusterIP
