apiVersion: v1
kind: Service
metadata:
  name: reverse-proxy-service
  labels:
    app: reverse-proxy
spec:
  selector:
    app: reverse-proxy
  ports:
    - name: http
      port: 80
      targetPort: 80
  type: ClusterIP
