apiVersion: apps/v1
kind: Deployment
metadata:
  name: browserquest-client
  labels:
    app: browserquest
    tier: client
spec:
  replicas: 3
  selector:
    matchLabels:
      app: browserquest
      tier: client
  template:
    metadata:
      labels:
        app: browserquest
        tier: client
    spec:
      containers:
        - name: client
          image: coloradostark/browserquest
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
