apiVersion: apps/v1
kind: Deployment
metadata:
  name: browserquest-server
  labels:
    app: browserquest
    tier: server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: browserquest
      tier: server
  template:
    metadata:
      labels:
        app: browserquest
        tier: server
    spec:
      containers:
        - name: server
          image: coloradostark/browserquest
          command: ["node", "server/js/main.js"]
          ports:
            - containerPort: 8000
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "750m"
              memory: "768Mi"
