apiVersion: v1
kind: ConfigMap
metadata:
  name: reverse-proxy-config
  namespace: default
  labels:
    app: reverse-proxy
data:
  nginx.conf: |
      events {
          worker_connections 1024;
      }
      
      http {
          include       mime.types;
          default_type  application/octet-stream;
      
          upstream websocket_backend {
              server browserquest-service:8000;
          }
      
          upstream frontend_backend {
              server browserquest-service:80;
          }
      
          server {
              listen 80;
      
              location / {
                  proxy_pass http://frontend_backend;
                  root /usr/share/nginx/html;
                  index index.html;
                  try_files $uri $uri/ /index.html;
              }
      
              location /ws/ {
                  proxy_pass http://websocket_backend;
                  proxy_http_version 1.1;
                  proxy_set_header Upgrade $http_upgrade;
                  proxy_set_header Connection "Upgrade";
                  proxy_set_header Host $host;
              }
          }
      }

