apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: ingress-nginx
  namespace: kube-system
spec:
  chart: ingress-nginx
  repo: https://kubernetes.github.io/ingress-nginx
  version: 4.10.0
  valuesContent: |-
    controller:
      service:
        type: NodePort
      extraArgs:
        enable-ssl-passthrough: ""
